### ISSUE TITLE
Transfer mode duplicates items with drawers

### ISSUE THREAD

**Issue by esotericist** [AnimeniacYuuto/InventoryTools#2]
Whenever you have a dolly containing an inventory while in transfer mode, attempting to transfer to drawers causes the first found stack to be placed in all empty slots, without actually deducting them from the source inventory. The result is duplicating that stack.

If you happen to do this to a storage controller, it duplicates that stack amongst all connected storage drawers with empty slots.

I tested this with both a vanilla chest and a storage drawer in the dolly as source, against vanilla chest (works as expected), as well as single drawer and controller array (to exhibit above issue).

As an aside, transfer mode with a dolly seems to ignore the locked state of storage drawers, such that a locked empty drawer slot will be filled. This may or may not be connected to the above error, but it's certainly a violation of the storage drawers model for inventory interaction, especially with a drawer controller.

**Comment by AnimeniacYuuto** [comment]
fixed via 8b237e5792a9bc0ec3b28fd35ba69cc98c2edc01

**Comment by esotericist** [comment]
Thank you again! New release downloaded and problem is verified resolved in our use case.
