### ISSUE TITLE
Dolly add option to blacklist all blocks from a Mod.

### ISSUE THREAD

**Issue by nmarshall23** [AnimeniacYuuto/InventoryTools#3]
Reika's Rotarycraft, does not play nicely with Frames or any mods that move his machines. 

Currently that means I have to list each block in the blacklist. I'd prefer to blacklist the entire mod and whitelist blocks from that mod, that don't cause crashes. 

Could you add an option to blacklist by mod?

**Comment by AnimeniacYuuto** [comment]
Feature added in 1.7.10-1.0.6
